### ISSUE TITLE
Create API in Nodejs

### ISSUE THREAD

**Issue by Reshail1** [samymassoud/paytabs_nodejs_api#1]
Hey, I want to create an endpoint in my nodejs api which uses paytabs. That API will be used for iOS and Android apps. 

But there are a lot of options that are required to create a paypage. 
Is there any way around?

**Comment by samymassoud** [comment]
Hey, Those option like Billing/Shipping address are mandatory for things like AVS (Address Verification) and Fraud detection, etc...

But sometime you can fix those information based on your usage, so I would recommend you to contact PayTabs support on their official Email support@paytabs.com

Will close this issue for now.
